import { MenuItem } from '../types';

// 從新易現炒店菜單提取的完整數據
export const MENU_DATA: MenuItem[] = [
    // 鐵板類
    { id: 'tb1', name: '鐵板羊肉', price: 150, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tb2', name: '鐵板牛柳', price: 150, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tb3', name: '鐵板豬柳', price: 150, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tb4', name: '鐵板雞柳', price: 150, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tb5', name: '鐵板鮮蚵', price: 150, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tb6', name: '鐵板類', price: 105, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tb7', name: '鐵板雞腿', price: 180, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tb8', name: '鐵板雞排', price: 230, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tb9', name: '鐵板牛柳', price: 230, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tb10', name: '鐵板鮮蚵', price: 230, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tb11', name: '鐵板豆腐', price: 200, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tb12', name: '鐵板杏鮑菇', price: 200, category: '鐵板類', imageUrl: '/placeholder.jpg', description: '' },

    // 燴飯類
    { id: 'hf1', name: '五更腸旺飯', price: 145, category: '燴飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'hf2', name: '海鮮豆腐煲', price: 145, category: '燴飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'hf3', name: '滑蛋蝦仁飯', price: 125, category: '燴飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'hf4', name: '滑蛋牛肉飯', price: 120, category: '燴飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'hf5', name: '蚵仔燴飯', price: 120, category: '燴飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'hf6', name: '羊肉燴飯', price: 120, category: '燴飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'hf7', name: '海鮮燴飯', price: 120, category: '燴飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'hf8', name: '蝦仁燴飯', price: 120, category: '燴飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'hf9', name: '牛肉燴飯', price: 110, category: '燴飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'hf10', name: '豬肉燴飯', price: 105, category: '燴飯類', imageUrl: '/placeholder.jpg', description: '' },

    // 現炒類
    { id: 'xc1', name: '皮蛋豆腐', price: 70, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc2', name: '麻婆豆腐', price: 150, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc3', name: '砂鍋蛤', price: 150, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc4', name: '炒杏鮑菇', price: 160, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc5', name: '炒螺肉', price: 190, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc6', name: '炒鹹豬肉', price: 180, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc7', name: '麻油豬肝', price: 180, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc8', name: '薑絲大腸', price: 190, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc9', name: '客家小炒', price: 190, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc10', name: '五更腸旺', price: 200, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc11', name: '糖醋豬柳', price: 190, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc12', name: '糖醋雞柳', price: 190, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc13', name: '宮保雞丁', price: 190, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc14', name: '宮保皮蛋', price: 190, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc15', name: '宮保牛柳', price: 190, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc16', name: '沙茶牛肉', price: 190, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc17', name: '蔥爆牛肉', price: 190, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc18', name: '沙茶羊肉', price: 210, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc19', name: '蔥爆羊肉', price: 210, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc20', name: '宮保羊肉', price: 210, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc21', name: '沙拉蝦球', price: 210, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc22', name: '清炒蝦仁', price: 210, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'xc23', name: '鹽水蝦', price: 220, category: '現炒類', imageUrl: '/placeholder.jpg', description: '' },

    // 三杯類
    { id: 'sb1', name: '三杯雞', price: 320, category: '三杯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'sb2', name: '三杯蝦', price: 230, category: '三杯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'sb3', name: '三杯雞翅', price: 220, category: '三杯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'sb4', name: '三杯大腸', price: 220, category: '三杯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'sb5', name: '三杯豆腐', price: 200, category: '三杯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'sb6', name: '三杯杏鮑菇', price: 200, category: '三杯類', imageUrl: '/placeholder.jpg', description: '' },

    // 炒飯類
    { id: 'cf1', name: '鮭魚雞粒炒飯', price: 120, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf2', name: '綜合炒飯', price: 120, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf3', name: '蝦仁炒飯', price: 120, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf4', name: '鮭魚炒飯', price: 120, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf5', name: '羊肉炒飯', price: 120, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf6', name: '牛肉炒飯', price: 110, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf7', name: '櫻花蝦炒飯', price: 110, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf8', name: '鹹豬肉炒飯', price: 110, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf9', name: '泡菜炒飯', price: 110, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf10', name: '香腸炒飯', price: 105, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf11', name: '肉絲炒飯', price: 100, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf12', name: '火腿炒飯', price: 100, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'cf13', name: '蛋炒飯', price: 90, category: '炒飯類', imageUrl: '/placeholder.jpg', description: '' },

    // 湯麵類
    { id: 'tm1', name: '麻油豬肝麵', price: 140, category: '湯麵類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tm2', name: '酸辣湯麵', price: 110, category: '湯麵類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tm3', name: '蚵仔湯麵', price: 110, category: '湯麵類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tm4', name: '鮮蝦餛飩麵', price: 105, category: '湯麵類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tm5', name: '海鮮湯麵', price: 110, category: '湯麵類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tm6', name: '榨菜肉絲麵', price: 100, category: '湯麵類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tm7', name: '豬肝湯麵', price: 100, category: '湯麵類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'tm8', name: '鍋燒(烏龍/意麵)', price: 100, category: '湯麵類', imageUrl: '/placeholder.jpg', description: '' },

    // 湯類
    { id: 't1', name: '麻油豬肝湯', price: 150, category: '湯類', imageUrl: '/placeholder.jpg', description: '大' },
    { id: 't2', name: '蚵仔湯', price: 150, category: '湯類', imageUrl: '/placeholder.jpg', description: '大' },
    { id: 't3', name: '鮮蝦餛飩湯', price: 130, category: '湯類', imageUrl: '/placeholder.jpg', description: '大' },
    { id: 't4', name: '酸辣湯', price: 130, category: '湯類', imageUrl: '/placeholder.jpg', description: '大' },
    { id: 't5', name: '大腸豬血湯', price: 120, category: '湯類', imageUrl: '/placeholder.jpg', description: '大' },
    { id: 't6', name: '豬肝湯', price: 90, category: '湯類', imageUrl: '/placeholder.jpg', description: '大' },
    { id: 't7', name: '蛤蜊湯', price: 90, category: '湯類', imageUrl: '/placeholder.jpg', description: '大' },
    { id: 't8', name: '蛋花湯', price: 70, category: '湯類', imageUrl: '/placeholder.jpg', description: '大' },
    { id: 't9', name: '麻油雞湯', price: 320, category: '湯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 't10', name: '番茄豆腐蛋花湯', price: 160, category: '湯類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 't11', name: '麻油豬肝湯', price: 80, category: '湯類', imageUrl: '/placeholder.jpg', description: '小' },
    { id: 't12', name: '蚵仔湯', price: 80, category: '湯類', imageUrl: '/placeholder.jpg', description: '小' },
    { id: 't13', name: '鮮蝦餛飩湯', price: 70, category: '湯類', imageUrl: '/placeholder.jpg', description: '小' },
    { id: 't14', name: '酸辣湯', price: 70, category: '湯類', imageUrl: '/placeholder.jpg', description: '小' },
    { id: 't15', name: '大腸豬血湯', price: 60, category: '湯類', imageUrl: '/placeholder.jpg', description: '小' },
    { id: 't16', name: '豬肝湯', price: 45, category: '湯類', imageUrl: '/placeholder.jpg', description: '小' },
    { id: 't17', name: '蛤蜊湯', price: 45, category: '湯類', imageUrl: '/placeholder.jpg', description: '小' },
    { id: 't18', name: '蛋花湯', price: 35, category: '湯類', imageUrl: '/placeholder.jpg', description: '小' },

    // 蔬菜類
    { id: 'sc1', name: '炒高麗菜', price: 90, category: '蔬菜類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'sc2', name: '炒青菜', price: 90, category: '蔬菜類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'sc3', name: '空心菜', price: 90, category: '蔬菜類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'sc4', name: '台灣啤酒', price: 40, category: '蔬菜類', imageUrl: '/placeholder.jpg', description: '' },

    // 飲料類
    { id: 'yl1', name: '醬爆高麗菜', price: 130, category: '飲料類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'yl2', name: '炸豆腐', price: 160, category: '飲料類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'yl3', name: '炸豆腐', price: 190, category: '飲料類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'yl4', name: '蝦仁煎蛋', price: 130, category: '飲料類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'yl5', name: '蚵仔煎蛋', price: 140, category: '飲料類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'yl6', name: '菜圃蛋', price: 110, category: '飲料類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'yl7', name: '蔥花蛋', price: 110, category: '飲料類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'yl8', name: '九香煎蛋', price: 110, category: '飲料類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'yl9', name: '汽水', price: 40, category: '飲料類', imageUrl: '/placeholder.jpg', description: '' },
    { id: 'yl10', name: '白飯', price: 15, category: '飲料類', imageUrl: '/placeholder.jpg', description: '' },
];

// 類別列表
export const CATEGORIES_LIST = [
    '鐵板類',
    '燴飯類',
    '現炒類',
    '三杯類',
    '炒飯類',
    '湯麵類',
    '湯類',
    '蔬菜類',
    '飲料類',
];
